Comment link
getfider/fider pull request #981
Opened 2021-07-21 20:06 UTC by indyteo

**Feature request:** [Ability to copy comments permalink](https://feedback.fider.io/posts/317/ability-to-copy-comments-permalink)

As mentioned in the post, it is inspired by GitHub's "Copy Link" feature on comments.

It first add a unique link for each comment, based on their ID.
For example, my reply on this post has the ID `#31419`, so the link would look like :
```
https://feedback.fider.io/posts/317/ability-to-copy-comments-permalink#comment-31419
```
Then, it add the corresponding HTML `id` attribute on a wrapping `div` around comments, so the page automatically scroll to the targeted comment.
On the other hand, it also create a `highlighted` state in the `ShowComment` component that slightly mutate the comment background (a bit darker than others) to stand out. When a click is performed outside of the comment's area, it get back to normal and the hash is removed from the URL (the part after the `#`).
Finally, an action in the comment's drop down, target the current comment (set the URL in the navigation bar, triggering the comment highlight and scroll), and copy that link into the user's clipboard. A feedback indicate whether the copy was successful or not (due to the lack of support of the Clipboard API by some old outdated browsers), and invite people to manually copy their page's URL if not.

If the hash don't match anything is simply get ignored, and if it looks like a comment reference but we're unable to find it, a notice is shown to the user, because it may happen when the original comment got deleted, or the URL was manually modified and is now invalid. It get instantly cleaned up to avoid further share of a partially invalid link.

***

I never really played with URL's hash before and found it funny to do this, this is why I decided to train with this idea, even if it only has 2 votes (which means none, except from the submitter and me 😆), and it only took me about an hour so it was fun 😄

2022-10-26 13:56 UTC, almereyda commented
@indyteo Would you like to rebase this branch on `main`, or merge it again?

Then we could try to find someone for a review. Eventually you can also request a review?

2022-10-26 14:27 UTC, indyteo commented
Hi @almereyda, I can have a look if it's not much work 👍

2024-09-09 12:54 UTC, mattwoberts commented
@indyteo Hi!

Few years later.... is there much demand for this, I'm happy to review it if you want to rebase / merge from main, although I appreciate it's probably not the highest thing on your priority list right now :)

2024-09-10 02:29 UTC, indyteo commented
Hi @mattwoberts,

Let's be honest, I completely forgot about this one! 😄

I'd be happy to rebase (and btw clean that awful git history with all those merge commits...) so you can review. After a (very) quick review of the work that was done, I guess it shouldn't cause much trouble to rebase.
I'll handle this tomorrow that's on my todo-list ☑️ 

Thanks

2024-09-10 16:11 UTC, indyteo commented
@mattwoberts yay! 🎉

This should be up-to-date, ready to review! 😊
The git history is definitely cleaner too 😄

2024-09-10 17:20 UTC, mattwoberts commented
Great, thanks :)

I'll take a look soon!

On Tue, Sep 10, 2024 at 5:12 PM Théo SZANTO ***@***.***>
wrote:

> @mattwoberts <https://github.com/mattwoberts> yay! 🎉
>
> This should be up-to-date, ready to review! 😊
> The git history is definitely cleaner too 😄
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/getfider/fider/pull/981#issuecomment-2341386992>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA2VDHUN7SE53LF5GHE5IDZV4K57AVCNFSM6AAAAABN4PRXNWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNBRGM4DMOJZGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-09-12 11:17 UTC, mattwoberts requested changes
Awesome stuff - some minor copy edit suggestions but all looks good!

2024-09-12 11:17 UTC, mattwoberts commented on locale/en/client.json
> +  "showpost.comment.copylink.success": "Successfully copied comment link to clipboard",
```suggestion
  "showpost.comment.copylink.success": "Comment link copied to clipboard",
```

2024-09-12 11:17 UTC, mattwoberts commented on locale/en/client.json
> +  "showpost.comment.copylink.error": "Could not copy comment link, please copy page URL",
```suggestion
  "showpost.comment.copylink.error": "Failed to copy comment link, please copy page URL",
```

2024-09-12 11:17 UTC, mattwoberts commented on locale/en/client.json
> +  "showpost.comment.unknownhighlighted": "Unknown comment ID #{id}",
```suggestion
  "showpost.comment.unknownhighlighted": "Invalid comment ID #{id}",
```

2024-09-12 18:14 UTC, mattwoberts approved these changes

2024-09-15 13:08 UTC, mattwoberts commented
In it comes :)

2024-09-15 13:08 UTC, merged

2024-09-15 16:30 UTC, almereyda commented
This is so nice and useful!

Looking forward to the next release.

2024-10-29 15:26 UTC, indyteo commented
@almereyda it just got released to v0.23.0 😄🎉

2024-10-29 15:37 UTC, mattwoberts commented
@indyteo You beat me to it ;)